#!/bin/bash

# Command line args
#
# #1 : version, format 17.1
# #2 : directory, for example los-17.1
#

VERSION=${1}
DIR=${2}
echo "Initialize lineage-${VERSION} in ${DIR}"

mkdir ${DIR}
cd ${DIR}

repo init -u git://github.com/LineageOS/android.git -b lineage-${VERSION} --depth 1

# Save some disk space by removing darwin stuff
sed -i '/darwin/d' .repo/manifests/default.xml

repo sync -j$(nproc --all) --no-tags --no-clone-bundle
git clone https://github.com/TheMuppets/proprietary_vendor_oneplus -b \
    lineage-${VERSION} vendor/oneplus

. build/envsetup.sh
breakfast cheeseburger && breakfast dumpling
